# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Environment
      directives:
        module: PSDscResources
      settings:
        Name: 'PATH'
        Ensure: 'Present'
        Value: "${env:OneDriveConsumer}\\Dev Settings\\POSHScripts"
        Target: 'Machine'
  configurationVersion: "0.2.0"